# File ReleaseBuild.yml
#
# Azure Pipeline to construct the final Nuget package for a binary release
# of CryptoBin
#
# Copyright (C) Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

trigger: none
pr: none

parameters:
- name: publish_nuget
  displayName: Publish as a Nuget Package
  type: boolean
  default: false
- name: version_major_minor
  displayName: Major and Minor Version
  type: string
  default: 2023.02
- name: version_patch
  displayName: Patch Version (0-65535)
  type: number
  default: 0
- name: version_label
  displayName: Version Label (e.g. '-rc', '-beta') (Use 'None' for none)
  type: string
  default: None

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: refs/tags/v9.1.1

extends:
  template: template-build.yml
  parameters:
    ${{ if startsWith(parameters.version_label, '-') }}:
      publish_version: ${{ parameters.version_major_minor }}.${{ parameters.version_patch }}${{ parameters.version_label }}
    ${{ else }}:
      publish_version: ${{ parameters.version_major_minor }}.${{ parameters.version_patch }}
    linux_container_image: 'ghcr.io/microsoft/mu_devops/ubuntu-22-build:1082f35'
    depends_on:
      - Build_AARCH64_ALL
      - Build_AARCH64_TINY_SHA
      - Build_AARCH64_MINIMAL_SHA_SM3
      - Build_AARCH64_SMALL_SHA_RSA
      - Build_AARCH64_STANDARD
      - Build_IA32_X64_ALL
      - Build_IA32_X64_TINY_SHA
      - Build_IA32_X64_MINIMAL_SHA_SM3
      - Build_IA32_X64_SMALL_SHA_RSA
      - Build_IA32_X64_STANDARD
    build_matrix:
      AARCH64_ALL:
        ArchList: 'AARCH64'
        Container: true
        VmImage: 'ubuntu-latest'
        ToolChain: 'GCC5'
        Flavor: 'ALL'
        CopyExtra: false
      AARCH64_TINY_SHA:
        ArchList: 'AARCH64'
        Container: true
        VmImage: 'ubuntu-latest'
        ToolChain: 'GCC5'
        Flavor: 'TINY_SHA'
        CopyExtra: false
      AARCH64_MINIMAL_SHA_SM3:
        ArchList: 'AARCH64'
        Container: true
        VmImage: 'ubuntu-latest'
        ToolChain: 'GCC5'
        Flavor: 'MINIMAL_SHA_SM3'
        CopyExtra: false
      AARCH64_SMALL_SHA_RSA:
        ArchList: 'AARCH64'
        Container: true
        VmImage: 'ubuntu-latest'
        ToolChain: 'GCC5'
        Flavor: 'SMALL_SHA_RSA'
        CopyExtra: false
      AARCH64_STANDARD:
        ArchList: 'AARCH64'
        Container: true
        VmImage: 'ubuntu-latest'
        ToolChain: 'GCC5'
        Flavor: 'STANDARD'
        CopyExtra: false
      IA32_X64_ALL:
        ArchList: 'IA32,X64'
        Container: false
        VmImage: 'windows-latest'
        ToolChain: 'VS2022'
        Flavor: 'ALL'
        CopyExtra: true
      IA32_X64_TINY_SHA:
        ArchList: 'IA32,X64'
        Container: false
        VmImage: 'windows-latest'
        ToolChain: 'VS2022'
        Flavor: 'TINY_SHA'
        CopyExtra: false
      IA32_X64_MINIMAL_SHA_SM3:
        ArchList: 'IA32,X64'
        Container: false
        VmImage: 'windows-latest'
        ToolChain: 'VS2022'
        Flavor: 'MINIMAL_SHA_SM3'
        CopyExtra: false
      IA32_X64_SMALL_SHA_RSA:
        ArchList: 'IA32,X64'
        Container: false
        VmImage: 'windows-latest'
        ToolChain: 'VS2022'
        Flavor: 'SMALL_SHA_RSA'
        CopyExtra: false
      IA32_X64_STANDARD:
        ArchList: 'IA32,X64'
        Container: false
        VmImage: 'windows-latest'
        ToolChain: 'VS2022'
        Flavor: 'STANDARD'
        CopyExtra: false
