/** @file
  Implements the EDK II Crypto Protocol/PPI services using the library services
  from BaseCryptLib and TlsLib.

  Copyright (C) Microsoft Corporation. All rights reserved.
  Copyright (c) 2019 - 2020, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/
#include <Base.h>
#include <Library/DebugLib.h>
#include <Library/SharedCryptoLib.h>
#include <Library/TlsLib.h>
#include <Protocol/SharedCryptoProtocol.h>

// MU_CHANGE - Remove BaseCryptLibServiceNotEnabled and macros
//             These were added for upstreaming into EDK2 and are
//             not used by Mu. They may eventually land in EDK2, at
//             which point we will need to make a decision about
//             their inclusion here.

/**
  Returns the version of the EDK II Crypto Protocol.

  @return  The version of the EDK II Crypto Protocol.

**/
UINTN
EFIAPI
CryptoServiceGetCryptoVersion (
  VOID
  )
{
  DEBUG ((DEBUG_ERROR, "CryptoServiceGetVersion is deprecated, use CryptoServiceGetCryptoVersion instead\n"));

  return -1; // TODO Deprecated, remove
}


VOID
EFIAPI
CryptoServiceGetLibraryVersion (
  UINT16 *MajorVersion,
  UINT16 *MinorVersion,
  UINT16 *RevisionVersion
  )
{

  if (MajorVersion != NULL) {
    *MajorVersion = VERSION_MAJOR;
  }
  if (MinorVersion != NULL) {
    *MinorVersion = VERSION_MINOR;
  }
  if (RevisionVersion != NULL) {
    *RevisionVersion = VERSION_REVISION;
  }
}


// MU_CHANGE [BEGIN]
// __REPLACEMENT_TAG__ - Autogenerated contents go here.
// MU_CHANGE [END]
