name: OneCrypto Publish Variant

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string
      publish_name:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        if: github.event_name == 'release'
        uses: actions/checkout@v6

      - name: Download Build Outputs (${{ inputs.variant }})
        uses: actions/download-artifact@v8
        with:
          name: onecrypto-package-${{ inputs.variant }}
          path: artifacts/${{ inputs.variant }}

      - name: Extract Packages (${{ inputs.variant }})
        shell: bash
        run: |
          mkdir -p publish/${{ inputs.variant }}
          cp -r artifacts/${{ inputs.variant }}/* publish/${{ inputs.variant }}/

      - name: Publish Bundle (${{ inputs.variant }})
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.publish_name }}
          path: publish/${{ inputs.variant }}/
          overwrite: true

      - name: Package Release Zip (${{ inputs.variant }})
        if: github.event_name == 'release'
        shell: bash
        run: |
          cd publish/${{ inputs.variant }}
          zip -r "../../${{ inputs.publish_name }}.zip" .

      - name: Upload Release Asset (${{ inputs.variant }})
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ inputs.publish_name }}.zip

      - name: Delete Intermediate Artifact (${{ inputs.variant }})
        uses: geekyeggo/delete-artifact@v5
        with:
          name: onecrypto-package-${{ inputs.variant }}
